# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update Datasets

on:
  push:
    paths:
      - agml/_assets/public_datasources.json
  pull_request:
    paths:
      - agml/_assets/public_datasources.json

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 setup.py install
    - name: Configure Git
      run: |
        git config user.name "AgML Dataset Update Bot"
        git config user.email "joshi.amoghn@gmail.com"
    - name: Update Datasets
      run: |
        python scripts/run_full_dataset_update.py
        git add agml/_assets/*
        git commit -m "Updated information for new dataset"
        git push origin dev
        
